export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FALIURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FALIURE:'LOGOUT_FALIURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_RESGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FALIURE:'USER_REGISTER_FALIURE'
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE:'GET_ALL_CATEGORIES_FAILURE'
}