export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FALIURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FALIURE:'LOGOUT_FALIURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_RESGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FALIURE:'USER_REGISTER_FALIURE'
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE:'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE',
}

export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FALIURE: 'GET_ALL_INITIAL_DATA_FALIURE',
}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST : 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FALIURE: 'GET_ALL_PRODUCTS_FALIURE'
}